services:
  frontend:
    container_name: vue3-app-server
    image: lincenying/images-mmf-blog-vite-vue3:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '80:80'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
